POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "Crab",
  "dateOfBirth": "13N6-04-12",
  "ssn": "09s786-122X",
  "gender": "other",
  "occupation": "self employeed"
}
